# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 20:27
from __future__ import unicode_literals

import account.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20, verbose_name='userName')),
                ('nick_name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20, null='111111')),
                ('photo', models.ImageField(storage=account.storage.AccountImageStorage(), upload_to='static/accountImage')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_visit', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('verify_code', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='AccountGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_Name', models.CharField(max_length=20)),
                ('authority', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='group',
            field=models.ForeignKey(null=-1, on_delete=django.db.models.deletion.CASCADE, to='account.AccountGroup'),
        ),
    ]
