# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20171017_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='group',
            field=models.IntegerField(choices=[(-2, 'locked'), (-1, 'unchecked'), (0, 'normal'), (1, 'admin')], default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AccountGroup',
        ),
    ]
