# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20171021_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='first_name',
            field=models.CharField(default='aa', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='last_name',
            field=models.CharField(default='aaaa', max_length=20),
            preserve_default=False,
        ),
    ]
