# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 04:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import news.storage


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsOnSpecialPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SpecialPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='news',
        ),
        migrations.RemoveField(
            model_name='newsonindex',
            name='news',
        ),
        migrations.RemoveField(
            model_name='newsonindextopbanner',
            name='news',
        ),
        migrations.RemoveField(
            model_name='topnews',
            name='news',
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='banner',
            field=models.ImageField(storage=news.storage.NewsImageStorage, upload_to='static/news/banner'),
        ),
        migrations.DeleteModel(
            name='AboutUs',
        ),
        migrations.DeleteModel(
            name='NewsOnIndex',
        ),
        migrations.DeleteModel(
            name='NewsOnIndexTopBanner',
        ),
        migrations.DeleteModel(
            name='TopNews',
        ),
        migrations.AddField(
            model_name='newsonspecialplace',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.News'),
        ),
        migrations.AddField(
            model_name='newsonspecialplace',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.SpecialPlace'),
        ),
    ]
