# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 14:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20171019_1005'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsStatus',
        ),
    ]
