# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_delete_newsstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='status',
            field=models.IntegerField(choices=[(1, 'Online'), (2, 'Draft')]),
        ),
    ]
