# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20171020_0027'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpecialPlace',
        ),
        migrations.AlterField(
            model_name='newsonspecialplace',
            name='place',
            field=models.IntegerField(choices=[(1, 'ABOUT US'), (2, 'INDEX TOP'), (3, 'INDEX'), (4, 'NEWS TOP')]),
        ),
    ]
