# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 15:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20171020_0037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='authorId',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='newsId',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
