# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20171021_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='has_comment',
            field=models.BooleanField(default=True),
        ),
    ]
