# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_activity_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='booked',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
