# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_signup_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
