# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 01:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_signup_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='time_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
