# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_auto_20171018_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='reserved',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
