# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 04:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0007_activity_reserved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='reserved',
        ),
    ]
