# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0008_remove_activity_reserved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.IntegerField(choices=[(1, 'ACTIVE'), (2, 'CANCELLED'), (3, 'EXPIRED'), (4, 'HOLD')]),
        ),
        migrations.DeleteModel(
            name='ActivityStatus',
        ),
    ]
