# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20171021_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='statue',
            field=models.IntegerField(choices=[(1, 'normal'), (2, 'blocked')]),
        ),
    ]
