# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 00:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20171021_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='statue',
            new_name='status',
        ),
    ]
